import { Grid } from "@mui/material";
import LoadingButton from "@mui/lab/LoadingButton";
import Head from "next/head";
import { useState } from "react";
import { useDispatch } from "react-redux";
import { SignUpUser } from "../../Redux/Actions/User/AuthAction";
import ToastHandler from "../../Utils/Toast/ToastHandler";
import { DesignForms, SignupForm } from "../../Utils/DesignUtilities/Form";
import { useRouter } from "next/router";

export default function Signup() {
  //constant utils here
  const dispatch = useDispatch();

  //State hooks here
  const [error, setError] = useState(false);
  const [loading, setLoading] = useState(false);

  //router defined here
  const router = useRouter();

  const signupuser = (e) => {
    e.preventDefault();
    const email = e.target.email.value;
    const password = e.target.password.value;
    const name = e.target.name.value;
    const cnfpassword = e.target.cnfpassword.value;

    if (email === "" || password === "" || name === "") {
      return setError(true);
    }

    if (password !== cnfpassword) {
      ToastHandler("warn", "Confirm password and password does not match");
      return setError(true);
    }

    const data = {
      data: {
        email,
        password,
        name,
      },
      onFailed: (message) => {
        setError(true);
        setLoading(false);
      },
      onSuccess: (data) => {
        setLoading(false);
        setError(fale);
        router.push("/welcome");
      },
    };

    setLoading(true);
    dispatch(SignUpUser(data));
  };
  return (
    <>
      <Head>
        <title>AOM Sigup</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Grid
        container
        sx={{
          margin: "auto",
          height: "100%",
        }}
        alignItems="center"
      >
        <Grid
          item
          lg={4}
          md={6}
          sm={12}
          style={{
            margin: "auto",
          }}
          justifyContent="center"
        >
          <form
            style={{
              width: "100%",
              textAlign: "center",
            }}
            onSubmit={signupuser}
          >
            {DesignForms(SignupForm, error)}
            <LoadingButton
              type="submit"
              variant="contained"
              style={{
                marginTop: "50px",
              }}
              loading={loading}
            >
              Sign Up
            </LoadingButton>
          </form>
        </Grid>
      </Grid>
    </>
  );
}
