import { Grid, Input } from "@mui/material";
import LoadingButton from "@mui/lab/LoadingButton";
import Head from "next/head";
import { useState } from "react";
import { useDispatch } from "react-redux";
import { LogInUser } from "../../Redux/Actions/User/AuthAction";

export default function Signin() {
  //constant utils here
  const dispatch = useDispatch();

  //State hooks here
  const [error, setError] = useState(false);
  const [loading, setLoading] = useState(false);

  const loginuser = (e) => {
    e.preventDefault();
    const data = {
      data: {
        email: e.target.username.value,
        password: e.target.password.value,
      },
      onFailed: (message) => {
        setError(true);
        setLoading(false);
      },
      onSuccess: (data) => {
        console.log(data);
        setLoading(false);
      },
    };

    setLoading(true);
    dispatch(LogInUser(data));
  };
  return (
    <>
      <Head>
        <title>AOM Sigin</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Grid
        container
        sx={{
          margin: "auto",
          height: "100%",
        }}
        alignItems="center"
      >
        <Grid
          item
          lg={4}
          md={6}
          sm={12}
          style={{
            margin: "auto",
          }}
          justifyContent="center"
        >
          <form
            style={{
              width: "100%",
              textAlign: "center",
            }}
            onSubmit={loginuser}
          >
            <Input
              placeholder="Username"
              fullWidth
              name="username"
              error={error}
            />
            <Input
              placeholder="Password"
              fullWidth
              style={{
                marginTop: "30px",
              }}
              name="password"
              error={error}
            />
            <LoadingButton
              type="submit"
              variant="contained"
              style={{
                marginTop: "50px",
              }}
              loading={loading}
            >
              Sign In
            </LoadingButton>
          </form>
        </Grid>
      </Grid>
    </>
  );
}
