import { Button } from "@mui/material";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useRouter } from "next/router";

export default function Home() {
  const router = useRouter();
  return (
    <div>
      <Head>
        <title>AOM</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Button
        onClick={() => {
          router.push("/Auth/Signin");
        }}
      >
        Sign In
      </Button>
      <Link href="/Auth/Signup">
        <Button>Sign Up</Button>
      </Link>
    </div>
  );
}
